### ISSUE TITLE
Is this ready to use

### ISSUE THREAD

**Issue by CvekCoding** [soyuka/symfony-messenger-redis#3]
Hello, @soyuka .

This is just a question - is your bundle ready to use (you didnt commit here from May)? I would like to use Redis as a message broker in my application, and looks like your bundle is only one which I can use for this.
Thanks.

**Comment by soyuka** [comment]
This bundle works with the symfony's messenger component. Also follow https://github.com/symfony/symfony/pull/28681 I'd like this to be in the standard edition. 
I'm using this and it works.
